alter table REF_IK_ORDER_LINE_TAG add constraint FK_REF_IK_ORDER_LINE_TAG_ON_ORDER_LINE foreign key (ORDER_LINE_ID) references REF_IK_ORDER_LINE(ID);
create index IDX_REF_IK_ORDER_LINE_TAG_ON_ORDER_LINE on REF_IK_ORDER_LINE_TAG (ORDER_LINE_ID);
