alter table REF_CK_ORDER_LINE add constraint FK_REF_CK_ORDER_LINE_ON_ORTEIDORENID foreign key (ORDER_TENANT_ID, ORDER_ENTITY_ID) references REF_CK_ORDER(TENANT_ID, ENTITY_ID);
create index IDX_REF_CK_ORDER_LINE_ON_ORTEIDORENID on REF_CK_ORDER_LINE (ORDER_TENANT_ID, ORDER_ENTITY_ID);
