alter table REF_CK_ORDER add constraint FK_REF_CK_ORDER_ON_CUTEIDCUENID foreign key (CUSTOMER_TENANT_ID, CUSTOMER_ENTITY_ID) references REF_CK_CUSTOMER(TENANT_ID, ENTITY_ID);
create index IDX_REF_CK_ORDER_ON_CUTEIDCUENID on REF_CK_ORDER (CUSTOMER_TENANT_ID, CUSTOMER_ENTITY_ID);
