alter table REF_DRIVER add constraint FK_REF_DRIVER_ON_PLATFORM_ENTITY foreign key (PLATFORM_ENTITY_ID) references REF_SAMPLE_PLATFORM_ENTITY(ID);
create index IDX_REF_DRIVER_ON_PLATFORM_ENTITY on REF_DRIVER (PLATFORM_ENTITY_ID);
