alter table REF_CAR_DETAILS_ITEM add constraint FK_REF_CAR_DETAILS_ITEM_ON_CAR_DETAILS foreign key (CAR_DETAILS_ID) references REF_CAR_DETAILS(ID);
create index IDX_REF_CAR_DETAILS_ITEM_ON_CAR_DETAILS on REF_CAR_DETAILS_ITEM (CAR_DETAILS_ID);
