alter table REF_DRIVER add constraint FK_REF_DRIVER_ON_CALLSIGN foreign key (CALLSIGN_ID) references REF_DRIVER_CALLSIGN(ID);
alter table REF_DRIVER add constraint FK_REF_DRIVER_ON_PLACE foreign key (PLACE_ID) references REF_PLACE(ID);
alter table REF_DRIVER add constraint FK_REF_DRIVER_ON_DRIVER_GROUP foreign key (DRIVER_GROUP_ID) references REF_DRIVER_GROUP(ID);
alter table REF_DRIVER add constraint FK_REF_DRIVER_ON_PLATFORM_ENTITY foreign key (PLATFORM_ENTITY_ID) references REF_SAMPLE_PLATFORM_ENTITY(ID);
create index IDX_REF_DRIVER_ON_CALLSIGN on REF_DRIVER (CALLSIGN_ID);
create index IDX_REF_DRIVER_ON_PLACE on REF_DRIVER (PLACE_ID);
create index IDX_REF_DRIVER_ON_DRIVER_GROUP on REF_DRIVER (DRIVER_GROUP_ID);
create index IDX_REF_DRIVER_ON_PLATFORM_ENTITY on REF_DRIVER (PLATFORM_ENTITY_ID);
