alter table REF_DRIVER_LICENSE add constraint FK_REF_DRIVER_LICENSE_ON_DRIVER foreign key (DRIVER_ID) references REF_DRIVER(ID);
create index IDX_REF_DRIVER_LICENSE_ON_DRIVER on REF_DRIVER_LICENSE (DRIVER_ID);
