alter table REF_CAR add constraint FK_REF_CAR_ON_COLOUR foreign key (COLOUR_ID) references REF_COLOUR(ID);
alter table REF_CAR add constraint FK_REF_CAR_ON_MODEL foreign key (MODEL_ID) references REF_MODEL(ID);
alter table REF_CAR add constraint FK_REF_CAR_ON_CAR_DOCUMENTATION foreign key (CAR_DOCUMENTATION_ID) references REF_CAR_DOCUMENTATION(ID);
alter table REF_CAR add constraint FK_REF_CAR_ON_TOKEN foreign key (TOKEN_ID) references REF_CAR_TOKEN(ID);
alter table REF_CAR add constraint FK_REF_CAR_ON_SELLER foreign key (SELLER_ID) references REF_SELLER(ID);
alter table REF_CAR add constraint FK_REF_CAR_ON_CURRENCY_CODE foreign key (CURRENCY_CODE) references REF_CURRENCY(CODE);
alter table REF_CAR add constraint FK_REF_CAR_ON_CATEGORY foreign key (CATEGORY_ID) references SYS_CATEGORY(ID);
create index IDX_REF_CAR_ON_COLOUR on REF_CAR (COLOUR_ID);
create index IDX_REF_CAR_ON_MODEL on REF_CAR (MODEL_ID);
create index IDX_REF_CAR_ON_CAR_DOCUMENTATION on REF_CAR (CAR_DOCUMENTATION_ID);
create index IDX_REF_CAR_ON_TOKEN on REF_CAR (TOKEN_ID);
create index IDX_REF_CAR_ON_SELLER on REF_CAR (SELLER_ID);
create index IDX_REF_CAR_ON_CURRENCY_CODE on REF_CAR (CURRENCY_CODE);
create index IDX_REF_CAR_ON_CATEGORY on REF_CAR (CATEGORY_ID);
